### PR TITLE
Remove global variables from job

### PR DESCRIPTION
**Pull request by ygalblum**
## Type of change

- [x] Refactor
- [x] Optimization

## Description

Global variables are in general a cause for issues; they can be set unexpectedly (or not set at all), they can be misused, etc. Instead, local variables, method parameters and instance fields should be used.

### CODE REVIEW

**Comment by ygalblum** [comment]
@rsevilla87 I didn't squash the commits to make it easier to review how each variable is removed

**Comment by rsevilla87** [comment]
> @rsevilla87 I didn't squash the commits to make it easier to review how each variable is removed

seems lt needs some rebase after the latest commits

**Comment by ygalblum** [comment]
> > @rsevilla87 I didn't squash the commits to make it easier to review how each variable is removed
> 
> seems lt needs some rebase after the latest commits

Done

**Review by rsevilla87 — APPROVED** [review]
lgtm

**Pull request merged**
