### PR TITLE
Allow running the test suite on a local Linux machine

### PR DESCRIPTION
**Pull request by ygalblum**
## Type of change

- [x] Optimization

## Description

The tests failed to run on a local Linux machine. To allow running it locally two main changes were required:
1. Run `opensearch` locally and instruct the tests to report to it
2. Run the tests with the locally built binary

In addition, instructions on running rootful Podman were added.

### CODE REVIEW

**Review by rsevilla87 — APPROVED** [review]
lgtm

**Review by rsevilla87 — APPROVED** [review]
I like this change, very useful thanks!

**Comment by rsevilla87** [comment]
Needs some rebase after merging your previous pr @ygalblum

**Comment by ygalblum** [comment]
> Needs some rebase after merging your previous pr @ygalblum

@rsevilla87 Done

**Review by vishnuchalla — APPROVED** [review]
lgtm

**Pull request merged**
