### PR TITLE
Template - add ReadFile to template map

### PR DESCRIPTION
**Pull request by ygalblum**
## Type of change

- [x] New feature

## Description

Allow reading data from a file into the rendered template

### CODE REVIEW

**Review by rsevilla87 — CHANGES_REQUESTED** [review]
Can you update the docs with this new function?

https://kube-burner.github.io/kube-burner/latest/reference/configuration/#template-functions

**Comment by ygalblum** [comment]
@rsevilla87 I've updated the documentation. Since none of the functions that were added manually were documented, I changed the section.
Not sure I understand what `GetSubnet24` receives or does. So, either let me know and I'll update this PR or just fix it later

**Comment by rsevilla87** [comment]
> @rsevilla87 I've updated the documentation. Since none of the functions that were added manually were documented, I changed the section. Not sure I understand what `GetSubnet24` receives or does. So, either let me know and I'll update this PR or just fix it later

Thanks for the updates, some of those functions are old and probably need to be removed, we can address that in the future, I don't want to delay this PR more time

**Review by rsevilla87 — APPROVED** [review]
lgtm

**Pull request merged**
